name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 0 */2 * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mirror Website
        run: |
          # Ensure wget is installed (usually pre-installed on Ubuntu runners)
          wget --version
          # Mirror the entire website to the root of the ./site directory
          wget --mirror --no-parent --convert-links --adjust-extension --page-requisites --no-clobber --base=./ https://minex.speedslicer.dev/ -P ./site
          find ./site -type f -exec sed -i 's|/resources|/actionevil/resources|g' {} +
          # Move the content to the root directory
          mv ./site/minex.speedslicer.dev/* ./
          mv ./site/minex.speedslicer.dev/.* ./ || true  # Move hidden files if any

      - name: List directory contents
        run: |
          # List contents of the site directory for debugging
          ls -R ./

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './' # Ensure the correct directory is being uploaded

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
